import { Inter } from 'next/font/google'
import './globals.css'
import "./layout.css"

import { Nav, } from '@/components'

export const metadata = {
  title: 'The Truth Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Nav />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
